### ISSUE TITLE
Sweep: Add go action to run make generate if *.go file changed

### ISSUE THREAD

**Issue by hanksudo** [hanksudo/sweep-playground#24]
### Details

- Add go action to run make generate if *.go file changed

<details>
<summary>Checklist</summary>

- [ ] `.github/workflows/go.yml`
> * Add a name for the action using the `name` keyword. For example, `name: Go`.
> • Specify that the action should be triggered on push events that involve changes to `.go` files. For example, `on: push: paths: '*.go'`.
> • Define a job for the action using the `jobs` keyword. For example, `jobs: build: runs-on: ubuntu-latest`.
> • In the job definition, specify the steps that the job should perform. The first step should be to check out the repository using the `actions/checkout@v2` action. The second step should be to run the `make generate` command. For example, `steps: - uses: actions/checkout@v2 - name: Run make generate run: make generate`.

</details>

**Comment by kevinlu1248** [comment]
Hey @hanksudo we're taking a look at this bug
